###!!!
### Always delete volumes when shutting down. I.e. use:
### ```
### docker compose down -v
### ```
### Otherwise agents might use stale certs.

version: "3.1"
services:
  pyhvrhub:
    build:
      dockerfile: Dockerfile-clean-inst.hub
      args:
        owner: ${owner}
      context: .
    container_name: pyhvrhub
    hostname: pyhvrhub
    ports:
      - "4340:4340"
    environment:
      - HUB_DATABASE_HOST=pghub
      - HUB_DATABASE_PORT=5432
      - HUB_DATABASE_NAME=pghub
      - DEPLOYMENT_ID=gidtest-1
      - DEPLOYMENT_GROUP_ID=gidtest
      - AGENT_1_ENDPOINT=pyhvragent-1-service
      - AGENT_2_ENDPOINT=pyhvragent-2-service
      - OVERRIDE_HUB_DATABASE_PASSWORD=Kiwi1234
      - OVERRIDE_HUB_DATABASE_USER=postgres
      - OVERRIDE_HUB_ADMIN_PASSWORD=Kiwi1234Kiwi1234
      - OVERRIDE_HUB_ADMIN_USER=admin
  pyhvragent-1:
    build:
      dockerfile: Dockerfile-clean-inst.agent
      args:
        owner: ${owner}
      context: .
    container_name: pyhvragent-1
    # ports:
    #   - "4340:4340"
    environment:
      - AGENT_ID=1
      - DEPLOYMENT_GROUP_ID=gidtest
  pyhvragent-2:
    build:
      dockerfile: Dockerfile-clean-inst.agent
      args:
        owner: ${owner}
      context: .
    container_name: pyhvragent-2
    # ports:
    #   - "4340:4340"
    environment:
      - AGENT_ID=2
      - DEPLOYMENT_GROUP_ID=gidtest
  
  pghub:
    image: postgres:12.8
    container_name: pghub
    environment:
      - POSTGRES_PASSWORD=Kiwi1234
      - POSTGRES_DB=pghub
  postgres-source:
    image: ${owner}/testdb:pg-hammerdb-empty
    container_name: postgres-source
    command: ["-c", "wal_level=logical"]
    environment:
      - POSTGRES_PASSWORD=Kiwi1234
      - POSTGRES_DB=tpcc
  postgres-target:
    image: ${owner}/testdb:pg-hammerdb-empty
    container_name: postgres-target
    command: ["-c", "wal_level=logical"]
    environment:
      - POSTGRES_PASSWORD=Kiwi1234
      - POSTGRES_DB=tpcc
