name: Test pyhvr
env:
  project: build-286712
  region: us

on: push

jobs:
  pytest_on_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Configure docker for GAR
        run: |
          gcloud auth configure-docker ${{ env.region }}-docker.pkg.dev -q
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Install all the required python modules for app, but also flake8 and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Install pyhvr
        run: |
          pip install .
      # TODO: check that generated code is up-to-date with source code
      - name: docker compose and pytest
        run: |
          cd docker-compose
          export owner=${{ env.region }}-docker.pkg.dev/${{ env.project }}/pyhvr
          docker-compose -f docker-compose-preconf.yaml up -d

          cd ..
          echo "Wait for HVR6 and all dependencies to be ready"
          while ! docker exec pyhvrhub nc postgres-source 5432 ; do sleep 1; done;
          while ! docker exec pyhvragent-1 nc localhost 4343 ; do sleep 1; done;
          while ! docker exec pyhvragent-2 nc localhost 4343 ; do sleep 1; done;
          docker exec pyhvrhub grep "Expiry date" /install/hvr.lic
          pytest --ignore tests/test_clean_install.py --ignore tests/test_user.py --ignore tests/test_duplicate_table_entry.py
          cd -
          docker-compose -f docker-compose-preconf.yaml down -v

          docker-compose -f docker-compose-clean-inst.yaml up -d
          cd ..
          echo "Wait for hubserver to come up"
          while ! docker exec pyhvrhub nc localhost 4340 ; do sleep 1; done;
          while ! docker exec pyhvragent-1 nc localhost 4343 ; do sleep 1; done;
          while ! docker exec pyhvragent-2 nc localhost 4343 ; do sleep 1; done;
          docker exec pyhvrhub grep "Expiry date" /install/hvr.lic
          docker cp pyhvrhub:/install/hvr.lic tests/hvr.lic
          pytest tests/test_clean_install.py tests/test_user.py
          cd -
          docker-compose  -f docker-compose-clean-inst.yaml down

          docker-compose -f docker-compose-clean-inst.yaml up -d
          cd ..
          echo "Wait for hubserver to come up"
          while ! docker exec pyhvrhub nc localhost 4340 ; do sleep 1; done;
          while ! docker exec pyhvragent-1 nc localhost 4343 ; do sleep 1; done;
          while ! docker exec pyhvragent-2 nc localhost 4343 ; do sleep 1; done;
          docker exec pyhvrhub grep "Expiry date" /install/hvr.lic
          docker cp pyhvrhub:/install/hvr.lic tests/hvr.lic
          pytest tests/test_duplicate_table_entry.py
          cd -
          docker-compose  -f docker-compose-clean-inst.yaml down
      # Run Flake8 test to confirm formatting of file etc.  This will use a custom config file .flake8
      - name: Flake8
        run: |
          flake8 --config .flake8
